# Site settings
name: Michael A. Hülfenhaus
description: "rapIT innovationBrain"
url: "www.hilfhilf.com"


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  mhuelfen
twitter_username: huelfe
linkedin_username: mhuelfen
xing_username: MichaelA_Huelfenhaus
email: huelfe@gmx.de



avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://www.gravatar.com/avatar/ef297dc9ef3674c2013eb61b9378ef72?s=250"


front_img: no
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"


favicon_img: no
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
